<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="EPBYMINW2898" name="com.atm.modulefive.webdriver.basics.runner.VoloTeaDemo" tests="3" failures="1" timestamp="05 Jun 2017 14:56:39 GMT" time="0.940" errors="0">
  <testcase name="FlightInformation" time="0.000" classname="com.atm.modulefive.webdriver.basics.runner.VoloTeaDemo">
    <skipped/>
  </testcase> <!-- FlightInformation -->
  <testcase name="SearchFlights" time="0.001" classname="com.atm.modulefive.webdriver.basics.runner.VoloTeaDemo">
    <skipped/>
  </testcase> <!-- SearchFlights -->
  <testcase name="VoloTeaSignIn" time="0.939" classname="com.atm.modulefive.webdriver.basics.runner.VoloTeaDemo">
    <failure type="java.lang.AssertionError" message="0000000000000000000000Logged in succesfully to with the authenticated USER expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: 0000000000000000000000Logged in succesfully to with the authenticated USER expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertFalse(Assert.java:62)
	at com.atm.modulefive.webdriver.basics.runner.VoloTeaDemo.VoloTeaSignIn(VoloTeaDemo.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoloTeaSignIn -->
</testsuite> <!-- com.atm.modulefive.webdriver.basics.runner.VoloTeaDemo -->
